### ISSUE TITLE
Fix bitHound Issues 🐞 🔨 🚶

### ISSUE THREAD

**Issue by clavecoder** [latticework/jali#105]
# Bug `chore`

## Details

| Version | Severity |
|:-|:-|
| v0.0.1 | 5 Documentation Error |

## Description
Fix various bitHound issues.

## Steps to Reproduce

1. Merge to master

## Defective Behavior
- [x] Resolve unused dependencies. See: https://www.bithound.io/github/latticework/jali/master/dependencies/npm
- [x] Resolve `@types/node` outdated: See: https://www.bithound.io/github/latticework/jali/master/dependencies/npm
- [x] linting disabled. See: https://github.com/latticework/jali/blob/master/.bithoundrc
- [x] esdoc dependency muted. See: https://www.bithound.io/github/latticework/jali/master/dependencies/npm/esdoc
- [x] Enable license checking. See: https://www.bithound.io/settings/github/latticework/jali
- [x] Fix code analysis issues for `argument-verifiers.ts`. See: https://www.bithound.io/github/latticework/jali/blob/111d6f4e93053fd2646fe9097ce46cc33479e1a0/packages/@jali-ms/util/src/argument-verifiers.ts
- [x] Fix code analysis issues for `iterables.ts`. See: https://www.bithound.io/github/latticework/jali/blob/111d6f4e93053fd2646fe9097ce46cc33479e1a0/packages/@jali-ms/util/src/iterables.ts

## Desired Behavior
All issues resolved.

**Comment by clavecoder** [comment]
Completed by #106
