### ISSUE TITLE
Add OpenHub Support ▶️️ 🔨 🎁

### ISSUE THREAD

**Issue by clavecoder** [latticework/jali#116]
# Enhancement `devenv`

## Definition
[//]: # ( Format follows http://blog.crisp.se/2014/09/25/david-evans/as-a-i-want-so-that-considered-harmful)
**In order to** visualize project code analytics,

**As a** `developer`,

**I want to** provide a Jali branch that contains source code that OpenHub can analyze.

## Tasks

- [ ] Create `open-hub` branch.
- [ ] Configure the OpenHub [Jali][open-hub-jail] project to reference the OpenHub branch.
- [ ] Monitor OpenHub project to ensure that the project is re-analyzed.

## Acceptance Criteria

- [ ] The OpenHub site shows the correct number of lines of code.

## Discussion
OpenHub does not recognize TypeScript source code. Therefore to provide OpenHub source code that
it can process, A branch should be created that preserves the JavaScript generated by the build process.

A future version if this Enhancement can require automated updates to the branch.
