### ISSUE TITLE
Project Documentation ️️️️▶️️ 🔨 🚶

### ISSUE THREAD

**Issue by clavecoder** [latticework/jali#119]
# Enhancement `devenv`

## Definition
[//]: # ( Format follows http://blog.crisp.se/2014/09/25/david-evans/as-a-i-want-so-that-considered-harmful)
In order to manage the Jali project,

As a `Developer`,

I want to maintain a full set of project documentation.

## Acceptance Criteria

- [x] **Completed standard documents**
- [x] README.md
- [x] LICENCE for MIT
- [x] CONTRIBUTING.md
- [x] github/ISSUE_TEMPLATE.md

- [x] **Completed supporting documents**
- [x] CREDITS.md
- [x] DESIGN.md
- [x] ISSUE-TEMPLATE-INSTRUCTIONS.md
