### ISSUE TITLE
Project Documentation ▶️️ 🔨 🚶

### ISSUE THREAD

**Issue by clavecoder** [latticework/jali#120]
# Enhancement `devenv`

## Definition
In order to manage the Jali project,

As a `Developer`,

I want to maintain a full set of project documentation.

## Changes from closed Enhancement #119 
- Added standard documents
  - CHANGELOG.md

- Added supporting documents
  - project/CHANGELOG-TEMPLATE.md
  - project/PROCEDURES.md
  - project/QUERIES.md

- Changed supporting documents
  - Moved documents
    - to project/CREDITS.md
    - to project/DESIGN.md
    - to project/ISSUE-TEMPLATE-INSTRUCTIONS.md

## Acceptance Criteria

- [ ] **Completed standard documents**
- [x] README.md
- [ ] CHANGELOG.md
- [x] LICENCE for MIT
- [x] CONTRIBUTING.md
- [x] github/ISSUE_TEMPLATE.md

- [x] **Completed supporting documents**
- [x] CREDITS.md
- [x] DESIGN.md
- [x] ISSUE-TEMPLATE-INSTRUCTIONS.md
