### ISSUE TITLE
Project Shell ▶️️ 🔨 ✅

### ISSUE THREAD

**Issue by clavecoder** [latticework/jali#122]
# Enhancement `change`

Replaces #1 
Completed by #7 

## Definition

In order to quickly get started developing as a Jali Contributor I want to clone and provision a Jali project development environment.

## Features

- `Vagrantfile` 
  - Provides the `jali` Ubuntu 16.04 graphical guest operating system using the `VirtualBox` provider.
  - Provisions the `jali` box using the `chef_zero` provisioner
- `main` cookbook in `site-cookbooks` that uses `Berksfile` to provision the `jali` box
  - The following components are provisioned.
    - Docker Service
    - The `Hack` font
    - `git`
    - NodeJS
    - Sphinx
    - VSCode
    - The latticework/jali GitHub repo

## Changed Features [chore]

- [x] Provides Ubuntu 16.04 instead of 14.04

## Tasks

- [x] Update Vagrantfile to Provide Ubuntu 16.04
- [x] Test provisioned configurations to ensure working result

## Acceptance Criteria

- [x] Cloning and provisioning [jali](https://github.com/latticework/jali) produces a fully initialized node project in a Vagrant graphical Unbuntu environment on Windows 10.
