### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by clavecoder** [latticework/jali#123]
# Jali Project Roadmap

## v0.1.0 (2017-02)

- ✨ [feat] New Features
  - [ ] 🔨 \[devenv\] (#2) Project Documentation (#120)
    - CHANGELOG.md
    - project/CHANGELOG-TEMPLATE.md
    - project/PROCEDURES.md
    - project/QUERIES.md

- Changed Features [change]

- Bug Fixes [fix]
-🎉 [change] Changed Features
- 🔧 Bug Fixes [fix]
  - 𝍖 \[jali-util\] (#82) Fix Known Test Failures (#103)
    - @jali-ms/util/src/iterables_reduce
      - `initialValue` can now be `null` or `undefined`
    - @jali-ms/util/src/iterables_slice
      - `begin` and `end` can now be `null` or `undefined`
    - @jali-ms/util/src/iterables_slice
      - now works if `begin` or `end` is negative
  - 📄 \[doc\] (#81) Bad scope in doc links                        [\[doc\]][doc] [#92][#92] ([#98][#98] — [69fecf5][69fecf5] — [@clavecoder][@clavecoder])
  - Manual page garbled for esdoc 0.5.x 🐞 🔧         [\[doc\]][doc] [#80][#80] ([#101][#101] — [1c6adb1][1c6adb1] — [@clavecoder][@clavecoder])
  - Mute Status Check Issue 🐞 🔨             [\[devenv\]][devenv] [#110][#110] ([#111][#111] — [d8462b9][d8462b9] — [@clavecoder][@clavecoder])
  - Fix bitHound Issues 🐞 🔨                 [\[devenv\]][devenv] [#105][#105] ([#106][#106] — 7 commits — [@clavecoder][@clavecoder])
  - Bad Contributing Document Formatting 🐞 🔨  [\[devenv\]][devenv] [#96][#96] ([#97][#97] — [c876ec1][c876ec1] — [@clavecoder][@clavecoder])
  - Bad README Links 🐞 🔨                      [\[devenv\]][devenv] [#91][#91] ([#97][#97] — [c876ec1][c876ec1] — [@clavecoder][@clavecoder])
  - Enhancement link broken 🐞 🔨               [\[devenv\]][devenv] [#85][#85] ([#97][#97] — [c876ec1][c876ec1] — [@clavecoder][@clavecoder])

## v0.0.1 (2017-01)

- ✨ [feat] New Features
  - [x] 𝍖 \[jali-util\] (#82) [JS] Argument validation functions (#90)
  - [x] 𝍖 \[jali-util\] (#82) [JS] Iterator Functions (#87)
  - [x] 𝍖 \[jali-util\] (#82) [JS] @jali-ms/util Type Guards (#86)
  - [x] 𝍖 \[jali-util\] (#82) [JS] Invalid State Error (#84)
  - [x] 𝍖 \[jali-util\] (#82) [JS] Argument Errors (#83)
  - [x] 🔨 \[devenv\] (#2) Project Shell (#1, #122)
  - [x] 🔨 \[devenv\] (#2) Project Documentation (#5, #119)
  - [x] 🔨 \[devenv\] (#2) Canary Builds (#113)
  - [x] 🔨 \[devenv\] (#2) [JS] Build Process (#4)

[devenv]: https://github.com/latticework/jali/issues/2
[doc]: https://github.com/latticework/jali/issues/81
[jali-util]: https://github.com/latticework/jali/issues/82
[#82]: https://github.com/latticework/jali/issues/82
[#81]: https://github.com/latticework/jali/issues/81
[#2]: https://github.com/latticework/jali/issues/2
