### ISSUE TITLE
Missing util TypeGuard esdoc comments 🐞 🔧 🎁

### ISSUE THREAD

**Issue by clavecoder** [latticework/jali#133]
# Bug `fix`

## Details

| Version | Severity |
|:-|:-|
| 0.1.0-prealpha.1 | 5 Documentation Error |

## Description

Missing esdoc comments for [type-guards.ts][type-guards-file]

## Steps to Reproduce

1. Open type-guards.ts (link above).
1. Notice missing esdoc comments.

## Defective Behavior

- Missing documentation

## Acceptance criteria.
- [ ] Adequate documentation on [type-guards.ts][type-guards-file]
- [ ] Successful esdoc build
- [ ] Overview updated with function summary.
- [ ] Documentation site is correct.

[type-guards-file]:  https://github.com/latticework/jali/blob/master/packages/%40jali-ms/util/src/type-guards.ts
