### ISSUE TITLE
Update to latest NPM packages 📋 🔩 🎁

### ISSUE THREAD

**Issue by clavecoder** [latticework/jali#137]
# Task: `work`

- Parent: #113 ▶️️

## Details

- [ ] Update all dependency packages to latest except for @types/node 6.x
- [ ] Remove all greenkeeper branches.
- [ ] Remove all greenkeeper issues.
