### ISSUE TITLE
Use Docker-based development environment ▶️️ 🔨 🎁

### ISSUE THREAD

**Issue by clavecoder** [latticework/jali#170]
[//]: # (                   )
[//]: # (                                                              )
[//]: # (Keep lines to 72 characters to leave room for the preview     )
[//]: # (pane while editing.                                           )
[//]: # (Note: Comment format explained by:                            )
[//]: # (http://stackoverflow.com/a/32190021                           )

# Enhancement `chore`

[//]: # ( Item Links )
- Completed by #PULL

## Definition

[//]: # ( User Story )
**In order to** develop Jali in a consistent environment across OS platforms and across team members

**As a** `contributor`,

**I want to** develop on a consistent guest os managed by Docker-based tooling,

**Whereas currently** Vagrant and Chef are used.

## Features

- [ ] Launch using Docker Compose
- [ ] Provide configurability per developer
- [ ] Provide default environment with graphical LTS distro of Ubuntu with VS Code installed
- [ ] Allow contributor to edit source on host system
- [ ] Provide onboarding documentation

## Tasks

- [ ] Provide onboarding documentation for Doker for Windows
- [ ] Define approach and determine subsequent tasks

## Acceptance Criteria

- [ ] Contributor can launch development environment from the command line of host OS
- [ ] Contributor can execute all necessary development tasks from within guest development containers
