### ISSUE TITLE
Update EcmaScript status to current 📋 🔩

### ISSUE THREAD

**Issue by clavecoder** [latticework/jali#189]
[//]: # (                   )
[//]: # (             )
[//]: # (                                                              )
[//]: # (Keep lines to 72 characters to leave room for the preview     )
[//]: # (pane while editing.                                           )
[//]: # (Note: Comment format explained by:                            )
[//]: # (http://stackoverflow.com/a/32190021                           )

[//]: # ( ############################################################ )
[//]: # ( # FORM: Task                                                 )
# Task: `<Task-type-name>`

- Parent: #120 ▶️️

## Details

- [ ] Update from TC39 2018-07
- [ ] Update from TS 2.9
- [ ] Update from TS 3.0
- [ ] Update from Babel 7 (latest)
