### ISSUE TITLE
Build single NPM package ▶️️ 🔨 ☑️

### ISSUE THREAD

**Issue by clavecoder** [latticework/jali#4]
# Enhancement `chore`
## Definition

In order to contribute to **jali**,
As a **Jali Contributor**,
I want to build a single NPM package.
## Tasks
- [x] Create `util` typescript source.
- [x] Add **tsc** support in build script.
- [x] Add **Babel** to build script.
- [x] Add **Webpack 2** to build script.
- [x] Add **Typings** support.
- [x] Add TAP-based test code.
- [x] Add code coverage.
- [x] Add documentation.
- [ ] Add conventional-changelog and versioning.
- [ ] Add module publishing scripts.
- [x] Publish package to NPM.
## Acceptance Criteria
- [x] Demonstrate the ability for **Jali Contributor** to use `npm run build` to build a single NPM package.
- [x] Packages must be a scoped to the NPM `jali-ms` organization.
- [x] The build process must use Webpack 2, Typescript, Babel and follow ng2 style for scoped modules.
- [x] Demonstrate usage of module from NPM.
