### ISSUE TITLE
Support ES2015+ features ▶️️ ✨🎁

### ISSUE THREAD

**Issue by clavecoder** [latticework/jali#78]
# Enhancement `feat`

## Definition
In order to JavaScript develop software forward-compatibly,

As a developer,

I want to develop from the list specified in 
[ECMASCRIPT-PROPOSALS.md](https://github.com/latticework/jali/blob/master/ecmascript-proposals.md),

Whereas currently compatibility is not tested.

## Tasks
- [ ] Add tests for EcmaScript proposals.
- [ ] Make changes (polyfills, TS -lib..., Babel plugins, etc) to reasonably support proposals.
- [ ] Rationalize ECMASCRIPT-PROPOSALS.md to conform to reality.

## Acceptance Criteria
- [ ] As many of `ES2015`, `ES2016`. and `ES2017` proposals are supported as possible.
- [ ] Stage 2 and Stage 3 proposals are supported as reasonable.
- [ ] Class and Property decorators are supported.

[jali]: https://github.com/latticework/jali
