### ISSUE TITLE
[JS] Argument Errors ▶️️ ✨ ☑️

### ISSUE THREAD

**Issue by clavecoder** [latticework/jali#83]
# Enhancement `feat`

## Definition
In order to consistently handle function argument errors,

As a developer,

I want to throw a specific error type for all common argument errors.

## Tasks
- [x] Create error types.
- [x] Create unit tests.
- [x] Create examples.
- [x] Create manual documentation.

## Acceptance Criteria
- [x] Error types
      - ☑️ Argument error are subclasses of more general error types.
      - ☑️ ArgumentError. Subclass of Error
      - ☑️ ArgumentFalsyError. Subclass of ArgumentError
      - ☑️ ArgumentEmptyStringError. Subclass of ArgumentFalsyError
      - ☑️ ArgumentFalseError. Subclass of ArgumentFalsyError
      - ☑️ ArgumentNanError. Subclass of ArgumentFalsyError
      - ☑️ ArgumentNullError. Subclass of ArgumentFalsyError
      - ☑️ ArgumentUndefinedError. Subclass of ArgumentFalsyError
      - ☑️ ArgumentUndefinedError. Subclass of ArgumentFalsyError
      - ☑️ ArgumentZeroError. Subclass of ArgumentFalsyError
      - ☑️ ArgumentWhitespaceStringError. Subclass of ArgumentError
      - ☑️ ArgumentTypeError. Subclass of ArgumentError
- [x] util/errors module
- [x] Unit tests with maximal code coverage
- [x] Complete documentation
      - ☑️ example code
      - ☑️ reference documentation
            - ☑️ esdoc code comments
            - ☑️ esdoc manual
