### ISSUE TITLE
[JS] Invalid State Error ▶️️ ✨ ☑️

### ISSUE THREAD

**Issue by clavecoder** [latticework/jali#84]
# Enhancement `feat`

## Definition
In order to fail-fast irrecoverable errors,

As a developer,

I want to throw an error that indicates the system is in an invalid state to continue.

## Tasks
- [x] Create error types.
- [x] Create unit tests.
- [x] Create examples.
- [x] Create manual documentation.

## Acceptance Criteria

- [x] InvalidStateError type Subclass of Error.
- [x] util/errors module
- [x] Unit tests with maximal code coverage
- [x] Complete documentation
      - [x] example code
      - [x] reference documentation
            - [x] esdoc code comments
            - [x] esdoc manual
