### ISSUE TITLE
[JS] @jali/util Type Guards ▶️️ ✨ ☑️

### ISSUE THREAD

**Issue by clavecoder** [latticework/jali#86]
# Enhancement `feat`

## Definition
In order to facilitate working with union types in TypeScript,

As a developer,

I want to use [User-Defined Type Guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) for common JavaScript types and idioms.

## Tasks

- [x] Create type guards
- [x] Create unit tests.
- [x] Create examples.
- [x] Create manual documentation.

## Acceptance Criteria

- [x] Type guards
      - ☑️ isError
      - ☑️ makeIsIterable: Generates deep-checking type guard for iterable of given type
      - ☑️ isIterable<T>
- [x] util/type-guards module
- [x] Unit tests with maximal code coverage
- [x] Complete documentation
      - ☑️ example code
      - ☑️ reference documentation
            - ☑️ esdoc code comments
            - ☑️ esdoc manual
