### ISSUE TITLE
[JS] @jali/util Iterator Functions ▶️️ ✨ ☑️

### ISSUE THREAD

**Issue by clavecoder** [latticework/jali#87]
# Enhancement `feat`

## Definition
In order to use any iterator as easily as an array in JavaScript,

As a Developer,

I want to use functions for any iterable that correspond to those of Array

## Tasks
- [x] Create error types.
- [x] Create unit tests.
- [x] Create examples.
- [x] Create manual documentation.

## Acceptance Criteria
- [x] Iterable functions
      - ☑ asArray
      - ☑ asIterable
      - ☑ concat
      - ☑ every
      - ☑ filter
      - ☑ find
      - ☑ includes
      - ☑ map
      - ☑ reduce
      - ☑ slice
      - ☑ some
      - ☑ toMap
- [x] util/iterables module
- [x] Unit tests with maximal code coverage
- [x] Complete documentation
      - ☑ example code
      - ☑ reference documentation
            - ☑ esdoc code comments
            - ☑ esdoc manual
