### ISSUE TITLE
[JS] Argument validation functions ▶️️ ✨ ☑️

### ISSUE THREAD

**Issue by clavecoder** [latticework/jali#90]
# Enhancement `feat`

## Definition
In order to fail-fast argument errors,

As a Developer,

I want to utilize standard argument validation functions that throw consistent errors.

## Tasks

- [x] Create error types.
- [x] Create unit tests.
- [x] Create examples.
- [x] Create manual documentation.

- [x] validation functions
      - ☑️ verifyArgument
      - ☑️ verifyArray
      - ☑️ verifyBoolean
      - ☑️ verifyDefined
      - ☑️ verifyFunction
      - ☑️ verifyIterable
      - ☑️ verifyNonEmpty
      - ☑️ verifyNonZero
      - ☑️ verifyNotNull
      - ☑️ verifyNotWhitespace
      - ☑️ verifyNumber
      - ☑️ verifyObject
      - ☑️ verifyString
      - ☑️ verifyTrue
      - ☑️ verifyTruthy
- [x] util/errors module
- [x] Unit tests with maximal code coverage
- [x] Complete documentation
      - ☑️ example code
      - ☑️ reference documentation
            - ☑️ esdoc code comments
            - ☑️ esdoc manual
